import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function open(page){await page.addInitScript(()=>{if(window!==top)return;localStorage.setItem('jh-onboarded','done');localStorage.setItem('jh-demonote','off');});await page.goto('/');await page.locator('[data-id="creations"]').click();}
test('内置柔和默认样式在新作品和重启后保留预设身份、下拉框及参数',async({page})=>{
  const soft={preset:'soft',background:'#f5f0f7',foreground:'#463b52',accent:'#806392',surface:'#fffcff',font:'sans',size:16,spacing:24,radius:20,edge:'curve'};
  await open(page);
  await page.locator('[data-id="settings"]').click();await page.locator('[data-stab="creations"]').click();
  await page.locator('#creationDefaultStyle').selectOption('preset:soft');await page.locator('#creationDefaultSave').click();await expect(page.locator('#creationDefaultStatus')).toContainText('已保存');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('seeker-creation-style')))).toEqual({name:'柔和',style:soft});
  await page.reload();await page.locator('[data-id="creations"]').click();await page.getByRole('button',{name:'+ 新建知识卡片',exact:true}).click();
  await expect(page.locator('#creationPreset')).toHaveValue('soft');await expect(page.locator('#creationPreset option:checked')).toHaveText('柔和');
  for(const key of ['background','foreground','accent','surface','font','size','spacing','radius'])await expect(page.locator(`[data-style="${key}"]`)).toHaveValue(String(soft[key]));
  const record=(await page.evaluate(()=>window.SeekerRT.db.list('platform_creations'))).find(r=>r.kind==='card');expect(record.style).toEqual(soft);
  await page.reload();await page.locator('[data-id="creations"]').click();await page.locator('.creation-list-item').filter({hasText:'新知识卡片'}).click();
  await expect(page.locator('#creationPreset')).toHaveValue('soft');await expect(page.locator('#creationPreset option:checked')).toHaveText('柔和');await expect(page.locator('[data-style="radius"]')).toHaveValue('20');
});
test('个人样式跨作品复用，默认值显式设置与重启保留，删除撤销及完整备份往返',async({page})=>{
  await open(page);await page.getByRole('button',{name:'+ 新建知识卡片',exact:true}).click();await page.locator('#creationPreset').selectOption('dark');await page.locator('[data-style="radius"]').fill('21');
  await page.getByRole('button',{name:'保存到我的样式',exact:true}).click();await page.locator('#personalStyleName').fill('夜间阅读');await page.locator('#personalStyleSave').click();await expect(page.locator('#creationPersonalStyle option')).toHaveCount(2);expect(await page.evaluate(()=>localStorage.getItem('seeker-creation-style'))).toBeNull();
  await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.locator('#creationSaveStatus')).toHaveText('已保存到本机');
  const style=(await page.evaluate(()=>window.SeekerRT.db.list('platform_creations'))).find(r=>r.kind==='style');
  await page.locator('[data-id="settings"]').click();await page.locator('[data-stab="creations"]').click();await page.locator('#creationDefaultStyle').selectOption(style.id);await page.locator('#creationDefaultSave').click();await expect(page.locator('#creationDefaultStatus')).toContainText('已保存');
  await page.getByRole('button',{name:'移除样式',exact:true}).click();await page.locator('.toast-undo').last().click();await expect(page.getByRole('button',{name:'移除样式',exact:true})).toBeVisible();
  await page.reload();await page.locator('[data-id="creations"]').click();await page.getByRole('button',{name:'+ 新建对比表',exact:true}).click();await expect(page.locator('#creationPreset')).toHaveValue('dark');await expect(page.locator('[data-style="radius"]')).toHaveValue('21');
  await page.locator('#creationPreset').selectOption('soft');await page.locator('#creationPersonalStyle').selectOption(style.id);await expect(page.locator('#creationPreset')).toHaveValue('dark');
  const event=page.waitForEvent('download');await page.evaluate(()=>window.SeekerRT.db.export(false));const backup=JSON.parse(await readFile(await(await event).path(),'utf8'));expect(backup.collections.platform_creations.filter(r=>r.kind==='style')).toHaveLength(1);expect(backup.preferences['seeker-creation-style']).toContain('夜间阅读');
  await page.evaluate(async b=>{localStorage.removeItem('seeker-creation-style');await window.SeekerRT.db.remove('platform_creations',b.collections.platform_creations.find(r=>r.kind==='style').id);await window.SeekerRT.db.import(JSON.stringify(b));},backup);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('seeker-creation-style')).style.radius)).toBe(21);expect((await page.evaluate(()=>window.SeekerRT.db.list('platform_creations'))).filter(r=>r.kind==='style')).toHaveLength(1);
});
test('对比表行列和时间线顺序可编辑、撤销、重启及导出',async({page})=>{
  await open(page);await page.evaluate(()=>{window.SeekerRT.ai.generate=()=>{throw Error('Manual edits must not call AI');};});
  await page.getByRole('button',{name:'+ 新建对比表',exact:true}).click();await page.locator('[data-table-col="1"]').fill('公交通勤');await page.locator('[data-table-row="0"] textarea').nth(1).fill('更省心');
  await page.locator('[data-table-add-row]').click();await page.locator('[data-table-add-col]').click();await page.locator('[data-table-remove-col="3"]').click();await page.getByRole('button',{name:'撤销修改',exact:true}).click();await expect(page.locator('[data-table-col]')).toHaveCount(4);
  await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.locator('#creationSaveStatus')).toHaveText('已保存到本机');await expect(page.frameLocator('#creationPreview iframe').locator('table')).toContainText('更省心');
  await page.getByRole('button',{name:'导出 / 分享',exact:true}).click();await expect(page.locator('#creationExportImage')).toBeVisible({timeout:15000});await page.locator('.modal .x').click();
  await page.getByRole('button',{name:'+ 新建',exact:true}).click();await page.getByRole('button',{name:'时间线',exact:true}).click();await page.locator('[data-event-title]').fill('确定主题');await page.locator('[data-event-add]').click();await page.locator('[data-event-title]').nth(1).fill('收集资料');await page.locator('[data-event-move="1"]').click();await expect(page.locator('[data-event-title]').first()).toHaveValue('收集资料');
  await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.locator('#creationSaveStatus')).toHaveText('已保存到本机');await page.reload();await page.locator('[data-id="creations"]').click();await page.locator('.creation-list-item').filter({hasText:'新时间线'}).click();await expect(page.locator('[data-event-title]').first()).toHaveValue('收集资料');await expect(page.locator('[data-event-title]').nth(1)).toHaveValue('确定主题');
});
test('AI 风格只读样式且不改默认值，Widget 预览隔离，应用后版本可恢复',async({page})=>{
  await open(page);await page.evaluate(async()=>{const rt=window.SeekerRT,available=rt.available;rt.available=f=>f==='textGeneration'||available(f);await rt.creations.save({id:'cr_edit',kind:'widget',title:'测试组件',content:{html:'<p>PRIVATE_TEXT</p>'},style:{preset:'minimal'},source:{},projectId:'',deleted:false},0);await(await import('/platform/creations/page.js')).openCreation('cr_edit');window.creationAIRequests=[];rt.ai.generate=req=>{window.creationAIRequests.push(req);return {done:Promise.resolve({text:JSON.stringify(window.creationAIResponse),stopReason:'stop'}),cancel(){}};};window.creationAIResponse={accent:'#334466',radius:19};});
  await page.getByRole('button',{name:'用文字调风格',exact:true}).click();await page.locator('#creationAIRequest').fill('调成蓝灰色');await page.locator('#creationAIGenerate').click();await expect(page.locator('#creationAIApply')).toBeEnabled();expect((await page.evaluate(()=>window.creationAIRequests))[0].untrusted).not.toContain('PRIVATE_TEXT');await page.locator('#creationAIApply').click();await expect(page.locator('[data-style="radius"]')).toHaveValue('19');expect(await page.evaluate(()=>localStorage.getItem('seeker-creation-style'))).toBeNull();
  await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.locator('#creationSaveStatus')).toHaveText('已保存到本机');
  await page.evaluate(()=>{window.creationAIResponse={html:'<button onclick="this.textContent=42">计算</button><script>try{parent.document.body.dataset.bad="yes"}catch(e){}</script>'};});await page.getByRole('button',{name:'AI 修改 Widget',exact:true}).click();await page.locator('#creationAIRequest').fill('增加计算按钮');await page.locator('#creationAIGenerate').click();await expect(page.locator('#creationAIPreview iframe')).toHaveAttribute('sandbox','allow-scripts');await page.frameLocator('#creationAIPreview iframe').getByRole('button',{name:'计算'}).click();await expect(page.frameLocator('#creationAIPreview iframe').getByRole('button',{name:'42'})).toBeVisible();expect(await page.evaluate(()=>document.body.dataset.bad)).toBeUndefined();
  await page.locator('#creationAIApply').click();await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.locator('#creationSaveStatus')).toHaveText('已保存到本机');await expect(page.frameLocator('#creationPreview iframe').getByRole('button',{name:'计算'})).toBeVisible();
  await page.getByText('修改记录（最近 20 个版本）',{exact:true}).click();await page.getByRole('button',{name:'恢复此版本',exact:true}).first().click();await expect(page.frameLocator('#creationPreview iframe').locator('p')).toHaveText('PRIVATE_TEXT');await expect(page.locator('[data-style="radius"]')).toHaveValue('19');
});

test('默认样式写失败保留旧设置，收藏保存失败保留名称与草稿',async({page})=>{
  await open(page);await page.locator('[data-id="settings"]').click();await page.locator('[data-stab="creations"]').click();await page.locator('#creationDefaultStyle').selectOption('preset:soft');await page.locator('#creationDefaultSave').click();await expect(page.locator('#creationDefaultStatus')).toContainText('已保存');const prior=await page.evaluate(()=>localStorage.getItem('seeker-creation-style'));
  await page.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='seeker-creation-style')throw Error('设置不可写');return set.call(this,key,value);};});await page.locator('#creationDefaultStyle').selectOption('preset:dark');await page.locator('#creationDefaultSave').click();await expect(page.locator('#creationDefaultStatus')).toContainText('设置不可写');expect(await page.evaluate(()=>localStorage.getItem('seeker-creation-style'))).toBe(prior);
  await page.locator('[data-id="creations"]').click();await page.getByRole('button',{name:'+ 新建知识卡片',exact:true}).click();await page.locator('#creationText').fill('未保存的正文');await page.evaluate(()=>{window.SeekerRT.creations.save=()=>Promise.reject(Error('样式磁盘不可写'));});await page.getByRole('button',{name:'保存到我的样式',exact:true}).click();await page.locator('#personalStyleName').fill('仍然保留');await page.locator('#personalStyleSave').click();await expect(page.locator('#personalStyleStatus')).toContainText('样式磁盘不可写');await expect(page.locator('#personalStyleName')).toHaveValue('仍然保留');await page.locator('.modal .x').click();await expect(page.locator('#creationText')).toHaveValue('未保存的正文');
});
